In [5]:
import numpy as np
vize = [10, 20, 30, 40]
final = [2, 60, 32, 50]

vize_np = np.array(vize)
final_np = np.array(final)

ortalama = (vize_np + final_np)/2
print(ortalama)

[ 6. 40. 31. 45.]


In [11]:
import numpy as np

# 2 boyutlu bir NumPy dizisi oluşturma
my_array = np.array([[1, 2, 3], [4, 5, 6]])

# NumPy dizisini ekrana yazdırma
print(my_array)

[[1 2 3]
 [4 5 6]]


In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
max_value = np.amax(arr)
print(max_value) # output: 5

5


In [16]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
max_value = np.amax(arr, axis=1)
print(max_value) # output: [3 6 9]

[3 6 9]


In [18]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
max_value = np.amax(arr, axis=1, keepdims=True)
print(max_value) # output: [[3], [6], [9]]

[[3]
 [6]
 [9]]


In [19]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
max_value = np.amax(arr,initial=0)
print(max_value) # output: 5

5
